package io.metalmynds.tractor.runner;

/*
 * Copyright 2001-2005 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.EnvironmentVariableCredentialsProvider;
import com.amazonaws.services.devicefarm.model.*;
import com.amazonaws.util.StringUtils;
import io.metalmynds.tractor.AWSDeviceFarm;
import io.metalmynds.tractor.AWSDeviceFarmException;
import io.metalmynds.tractor.frameworks.*;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;

/**
 * Goal which executes amazon device farm tests*
 */
@Mojo(name = "integration-test")
public class DeviceFarmRunner
        extends AbstractMojo {
    /**
     * Location of the file.
     *
     * @parameter property="project.build.directory"
     * @required
     */
    private File outputDirectory;

    /**
     * Name of Device Farm Project.
     */
    @Parameter(property = "project.name", required = true)
    private String projectName;

    /**
     * Version of Appium.
     */
    @Parameter(property = "appium.version", defaultValue = "1.6.5", required = true)
    private String appiumVersion;

    /**
     * Framework Type BUILTIN_EXPLORER, APPIUM_JAVA_JUNIT, APPIUM_JAVA_TESTNG, APPIUM_PYTHON, APPIUM_WEB_JAVA_JUNIT, APPIUM_WEB_JAVA_TESTNG, APPIUM_WEB_PYTHON, CALABASH, INSTRUMENTATION, UIAUTOMATION, UIAUTOMATOR, XCTEST, XCTEST_UI
    */
     @Parameter(property = "test.framework.type", required = true)
    private TestType frameworkType;

    /**
     * Filename of the Zipped Tests generated by Maven.
     */
    @Parameter(property = "upload.test.filename", required = true)
    private String testFilename;

    /**
     * Device Pool Name.
     */
    @Parameter(property = "device.pool.name", required = true)
    private String devicePoolName;

    /**
     * Filename of the System Under Test Package Android or iOS to upload.
     */
    @Parameter(property = "upload.application.filename", required = true)
    private String applicationFilename;

    /**
     * AWS Role ARN
     */
    @Parameter(property = "aws.role.arn")
    private String roleArn;

    /**
     * Filename of a file containing test data to upload.
     */
    @Parameter(property = "upload.test.data.filename")
    private String testDataFilename;

    /**
     * NOT IMPLEMENTED Filenames of auxiliary Packages Android or iOS to upload.
     */
    @Parameter(property = "upload.auxiliary.filenames") // NOT IMPLEMENTED
    private String auxiliaryFilenames;

    /**
     * Device Wifi Enabled
     */
    @Parameter(property = "device.state.wifi", defaultValue = "true")
    private Boolean deviceWifi;

    /**
     * Device Bluetooth Enabled
     */
    @Parameter(property = "device.state.bluetooth", defaultValue = "false")
    private Boolean deviceBluetooth;

    /**
     * Device GPS Enabled
     */
    @Parameter(property = "device.state.gps", defaultValue = "false")
    private Boolean deviceGps;

    /**
     * Device NFC Enabled
     */
    @Parameter(property = "device.state.nfc", defaultValue = "true")
    private Boolean deviceStateNfc;

    /**
     * Device Latitude
     */
    @Parameter(property = "device.state.latitude", defaultValue = "47.6204")
    private Double deviceLatitude;

    /**
     * Device Longitude
     */
    @Parameter(property = "device.state.longitude", defaultValue = "-122.3491")
    private Double deviceLongitude;

    /**
     * Device Locale en_US
     */
    @Parameter(property = "device.state.locale", defaultValue = "en_US")
    private String deviceLocale;

    /**
     * Prefix to Test Run Name Generated.
     */
    @Parameter(property = "run.name.prefix", defaultValue = "Run")
    private String runNamePrefix;

    /**
     * Test Run Timeout in Minutes.
     */
    @Parameter(property = "run.timeout.minutes", required = true)
    private Integer runTimeoutMinutes;

    /**
     * Billing Method
     */
    @Parameter(property = "run.billing.method", defaultValue = "METERED")
    private String runBillingMethod;

    /**
     * Comma separated list of paths to retrieve artifacts from host machine. E.g $WORKING_DIRECTORY/report/fooa.txt,$WORKING_DIRECTORY/foob.txt
     */
    @Parameter(property = "host.artifact.paths", defaultValue = "$WORKING_DIRECTORY")
    private String hostArtifactPaths;

    /**
     * Comma separated list of paths to retrieve artifacts from iOS device.
     */
    @Parameter(property = "device.ios.artifact.paths")
    private String deviceiOSArtifactPaths;

    /**
     * Comma separated list of paths to retrieve artifacts from Android device.
     */
    @Parameter(property = "device.android.artifact.paths")
    private String deviceAndroidArtifactPaths;

    /**
     * Type of Network profile.
     */
    @Parameter(property = "device.network.profile.type", defaultValue = "PRIVATE")
    private NetworkProfileType deviceNetworkProfileType;

    /**
     * Name of Network profile to use.
     */
    @Parameter(property = "device.network.profile.name", defaultValue = "FULL")
    private String deviceNetworkProfileName;

    /**
     * Fuzz Event Count value.
     */
    @Parameter(property = "framework.fuzz.event.count")
    private String frameworkFuzzEventCount;

    /**
     * Fuzz Throttle value.
     */
    @Parameter(property = "framework.fuzz.throttle")
    private String frameworkFuzzThrottle;

    /**
     * Fuzz Seed value.
     */
    @Parameter(property = "framework.fuzz.seed")
    private String frameworkFuzzSeed;

    /**
     * Explorer Username.
     */
    @Parameter(property = "framework.explorer.username")
    private String frameworkExplorerUsername;

    /**
     * Explorer Password.
     */
    @Parameter(property = "framework.explorer.password")
    private String frameworkExplorerPassword;

    /**
     * Tests to Execute using the JUnit, Python, TestNG frameworks both Web and Native.
     */
    @Parameter(property = "framework.appium.tests")
    private String frameworkAppiumTests;

    /**
     * Calabash Features to execute.
     */
    @Parameter(property = "framework.calabash.features")
    private String frameworkCalabashFeatures;

    /**
     * Calabash Tags to use.
     */
    @Parameter(property = "framework.calabash.tags")
    private String frameworkCalabashTags;

    /**
     * Calabash Profile to use.
     */
    @Parameter(property = "framework.calabash.profile")
    private String frameworkCalabashProfile;

    /**
     * Instrumentation JUnit Artifact to use.
     */
    @Parameter(property = "framework.instrumentation.junit.artifact")
    private String frameworkInstrumentationjUnitArtifact;

    /**
     * Instrumentation JUnit Filter to apply.
     */
    @Parameter(property = "framework.instrumentation.junit.filter")
    private String frameworkInstrumentationjUnitFilter;

    /**
     * UIAutomator Artifact to use.
     */
    @Parameter(property = "framework.uiautomator.artifact")
    private String frameworkUIAutomatorArtifact;

    /**
     * UIAutomator Filter to apply.
     */
    @Parameter(property = "framework.uiautomator.filter")
    private String frameworkUIAutomatorFilter;

    /**
     * UIAutomation Artifact to use.
     */
    @Parameter(property = "framework.uiautomation.artifact")
    private String frameworkUIAutomationArtifact;

    /**
     * XCTest Artifact to use.
     */
    @Parameter(property = "framework.xctest.artifact")
    private String frameworkXCTestArtifact;

    /**
     * XCTest Filter to apply.
     */
    @Parameter(property = "framework.xctest.filter")
    private String frameworkXCTestFilter;

    /**
     * XCTest UI Artifact to use.
     */
    @Parameter(property = "framework.xctest.ui.artifact")
    private String frameworkXCTestUIArtifact;

    /**
     * XCTest UI Filter to apply.
     */
    @Parameter(property = "framework.xctest.ui.filter")
    private String frameworkXCTestUIFilter;


    public void execute()
            throws MojoExecutionException {
        AWSDeviceFarm client;
        AWSCredentials credentials;

        if (StringUtils.isNullOrEmpty(roleArn)) {
            client = new AWSDeviceFarm(roleArn);
        } else {
            credentials = (AWSCredentials) new EnvironmentVariableCredentialsProvider();
            client = new AWSDeviceFarm(credentials);
        }

        Project project = null;

        try {
            project = client.getProject(projectName);
            getLog().debug(String.format("Device Farm Project Arn: %s", project.getArn()));
        } catch (Exception ex) {
            throw new MojoExecutionException(String.format("Get Device Farm Project '%s' failed!", projectName), ex);
        }

        Upload appUpload = null;

        try {
            if (Files.exists(Paths.get(applicationFilename))) {
                appUpload = client.uploadApp(project, applicationFilename);
                getLog().debug(String.format("Upload Mobile Application Arn: %s", appUpload.getArn()));
            } else {
                throw new FileNotFoundException(applicationFilename);
            }
        } catch (Exception ex) {
            throw new MojoExecutionException("Upload System Under Test Package Failed!", ex);
        }

        ScheduleRunTest testSchedule = new ScheduleRunTest();

        try {

            if (!StringUtils.isNullOrEmpty(testFilename)) {

                if (Files.exists(Paths.get(testFilename))) {

                    switch (frameworkType) {

                        case BUILTIN_FUZZ: {
                            Map<String, String> parameters = new HashMap<String, String>();

                            if (frameworkFuzzEventCount != null && !frameworkFuzzEventCount.isEmpty()) {
                                parameters.put("event_count", frameworkFuzzEventCount);
                            }

                            if (frameworkFuzzThrottle != null && !frameworkFuzzThrottle.isEmpty()) {
                                parameters.put("throttle", frameworkFuzzThrottle);
                            }

                            if (frameworkFuzzSeed != null && !frameworkFuzzSeed.isEmpty()) {
                                parameters.put("seed", frameworkFuzzSeed);
                            }

                            testSchedule
                                    .withType(frameworkType)
                                    .withParameters(parameters);
                            break;
                        }

                        case BUILTIN_EXPLORER: {
                            Map<String, String> parameters = new HashMap<String, String>();

                            if (frameworkExplorerUsername != null && !frameworkExplorerUsername.isEmpty()) {
                                parameters.put("username", frameworkExplorerUsername);
                            }

                            if (frameworkExplorerPassword != null && !frameworkExplorerPassword.isEmpty()) {
                                parameters.put("password", frameworkExplorerPassword);
                            }

                            testSchedule
                                    .withType(frameworkType)
                                    .withParameters(parameters);
                            break;
                        }

                        case APPIUM_JAVA_JUNIT: {
                            AppiumJavaJUnitTest test = new AppiumJavaJUnitTest.Builder()
                                    .withTests(frameworkAppiumTests)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn());

                            testSchedule.addParametersEntry("appium_version", appiumVersion);
                            break;
                        }

                        case APPIUM_JAVA_TESTNG: {
                            AppiumJavaTestNGTest test = new AppiumJavaTestNGTest.Builder()
                                    .withTests(frameworkAppiumTests)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn());

                            testSchedule.addParametersEntry("appium_version", appiumVersion);
                            break;
                        }

                        case APPIUM_PYTHON: {
                            AppiumPythonTest test = new AppiumPythonTest.Builder()
                                    .withTests(frameworkAppiumTests)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn());

                            testSchedule.addParametersEntry("appium_version", appiumVersion);
                            break;
                        }

                        case APPIUM_WEB_JAVA_JUNIT: {
                            AppiumWebJavaJUnitTest test = new AppiumWebJavaJUnitTest.Builder()
                                    .withTests(frameworkAppiumTests)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn());

                            testSchedule.addParametersEntry("appium_version", appiumVersion);
                            break;
                        }

                        case APPIUM_WEB_JAVA_TESTNG: {
                            AppiumWebJavaTestNGTest test = new AppiumWebJavaTestNGTest.Builder()
                                    .withTests(frameworkAppiumTests)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn());

                            testSchedule.addParametersEntry("appium_version", appiumVersion);
                            break;
                        }

                        case APPIUM_WEB_PYTHON: {
                            AppiumWebPythonTest test = new AppiumWebPythonTest.Builder()
                                    .withTests(frameworkAppiumTests)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn());

                            testSchedule.addParametersEntry("appium_version", appiumVersion);
                            break;
                        }

                        case CALABASH: {
                            CalabashTest test = new CalabashTest.Builder()
                                    .withFeatures(frameworkCalabashFeatures)
                                    .withTags(frameworkCalabashTags)
                                    .withProfile(frameworkCalabashProfile)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            Map<String, String> parameters = new HashMap<String, String>();
                            if (test.getTags() != null && !test.getTags().isEmpty()) {
                                parameters.put("tags", test.getTags());
                            }
                            if (test.getProfile() != null && !test.getProfile().isEmpty()) {
                                parameters.put("profile", test.getProfile());
                            }
                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn())
                                    .withParameters(parameters);
                            break;
                        }

                        case INSTRUMENTATION: {
                            InstrumentationTest test = new InstrumentationTest.Builder()
                                    .withArtifact(frameworkInstrumentationjUnitArtifact)
                                    .withFilter(frameworkInstrumentationjUnitFilter)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn())
                                    .withParameters(new HashMap<String, String>())
                                    .withFilter(test.getFilter());
                            break;
                        }

                        case UIAUTOMATOR: {
                            UIAutomatorTest test = new UIAutomatorTest.Builder()
                                    .withTests(frameworkUIAutomatorArtifact)
                                    .withFilter(frameworkUIAutomatorFilter)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn())
                                    .withParameters(new HashMap<String, String>())
                                    .withFilter(test.getFilter());

                            break;
                        }

                        case UIAUTOMATION: {
                            UIAutomationTest test = new UIAutomationTest.Builder()
                                    .withTests(frameworkUIAutomationArtifact)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withTestPackageArn(upload.getArn());
                            break;
                        }

                        case XCTEST: {
                            XCTestTest test = new XCTestTest.Builder()
                                    .withTests(frameworkXCTestArtifact)
                                    .withFilter(frameworkXCTestFilter)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withFilter(test.getFilter())
                                    .withTestPackageArn(upload.getArn());
                            break;
                        }

                        case XCTEST_UI: {
                            XCTestUITest test = new XCTestUITest.Builder()
                                    .withTests(frameworkXCTestUIArtifact)
                                    .withFilter(frameworkXCTestUIFilter)
                                    .build();

                            Upload upload = client.uploadTest(project, test);

                            testSchedule
                                    .withType(frameworkType)
                                    .withFilter(test.getFilter())
                                    .withTestPackageArn(upload.getArn());
                            break;
                        }

                    }

                } else {
                    throw new FileNotFoundException(testFilename);
                }
            }
        } catch (Exception ex) {
            throw new MojoExecutionException("Upload Test Package Failed!", ex);
        }

        ScheduleRunConfiguration runConfiguration = new ScheduleRunConfiguration();

        CustomerArtifactPaths customerArtifactPaths = new CustomerArtifactPaths();

        if (!StringUtils.isNullOrEmpty(hostArtifactPaths)) {
            customerArtifactPaths.setDeviceHostPaths(Arrays.asList(hostArtifactPaths.split(",")));
        }

        if (!StringUtils.isNullOrEmpty(deviceiOSArtifactPaths)) {
            customerArtifactPaths.setIosPaths(Arrays.asList(deviceiOSArtifactPaths.split(",")));
        }

        if (!StringUtils.isNullOrEmpty(deviceAndroidArtifactPaths)) {
            customerArtifactPaths.setAndroidPaths(Arrays.asList(deviceAndroidArtifactPaths.split(",")));
        }

        if (!StringUtils.isNullOrEmpty(testDataFilename)) {

            String testData;

            try {

                if (Files.exists(Paths.get(testDataFilename))) {
                    testData = new String(Files.readAllBytes(Paths.get(testDataFilename)));
                } else {
                    throw new FileNotFoundException(testDataFilename);
                }

                Upload extraData = client.uploadExtraData(project, testData);

                runConfiguration.setExtraDataPackageArn(extraData.getArn());

            } catch (Exception ex) {
                throw new MojoExecutionException(String.format("Failed Uploading Test Data from %s", testDataFilename), ex);
            }

        }

        DevicePool devicePool;

        try {

            devicePool = client.getDevicePool(project, devicePoolName);

        } catch (AWSDeviceFarmException ex) {
            throw new MojoExecutionException(String.format("Finding Device Pool '%s' Failed!", devicePoolName), ex);
        }

        runConfiguration.setBillingMethod(runBillingMethod);

        Location location = new Location();

        location.setLatitude(deviceLatitude);

        location.setLongitude(deviceLongitude);

        runConfiguration.setLocation(location);

        Radios radio = new Radios();

        radio.setWifi(deviceWifi);

        radio.setBluetooth(deviceBluetooth);

        radio.setGps(deviceGps);

        radio.setNfc(deviceStateNfc);

        runConfiguration.setRadios(radio);

        NetworkProfile networkProfile = new NetworkProfile().withType(deviceNetworkProfileType).withName(deviceNetworkProfileName);

        runConfiguration.setNetworkProfileArn(networkProfile.getArn());

        runConfiguration.setCustomerArtifactPaths(customerArtifactPaths);

        String runName = String.format("%s_%s", runNamePrefix, UUID.randomUUID().toString());

        getLog().info(String.format("Starting Run! Name: %s", runName));

        ScheduleRunResult run = client.scheduleRun(project.getArn(), runName, testSchedule.getTestPackageArn(), devicePool.getArn(), testSchedule, runTimeoutMinutes, runConfiguration);

        getLog().debug(String.format("Scheduled Run Arn: %s", run.getRun().getArn()));




    }
}
